/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;


import eu.hansolo.steelseries.gauges.Radial;
import java.awt.Color;

/**
 *
 * @author javiermg
 */
public class Velocimetro extends javax.swing.JPanel {

    Radial gauge;
    
    /**
     * Creates new form Velocimetro2
     */
    public Velocimetro() {
        
        gauge = new Radial();
        
        this.setBounds(10,50,300,300);
        this.setBackground(Color.gray);
        
        gauge.setBounds(0, 0, 300, 300);
        gauge.setMaxValue(300);
        gauge.setTitle("Velocimetro");
        gauge.setUnitString("km/h");
        
        
        this.add(gauge);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public void actualizarValor(Double v){
        gauge.setValueAnimated(v);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
