/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.Salpicadero;
import GUI.Palanca;
import javax.swing.JFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author javiermg
 */
public class Vista extends javax.swing.JPanel {

    private JFrame f;
    private Salpicadero salpicadero;
    private Mandos mandos;
    private Palanca palanca;
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        InicializarVentana();
    }
    
    private void InicializarVentana()
    {
       salpicadero = new Salpicadero();
       mandos = new Mandos();
       palanca = new Palanca(mandos);
       InicializarJFrame();
    }
    
    private void InicializarJFrame()
    {
       f = new JFrame("Coche");
       f.add(mandos);
       f.add(salpicadero);
       f.add(palanca);
       f.setSize(1200,800);    
       f.setLayout(null);    
       f.setVisible(true); 
        //Cerrar aplicación al cerrar ventana
       FuncionCerrarVentana();
    }
    
    private void FuncionCerrarVentana()
    {
         f.addWindowListener( new WindowAdapter() { 
           @Override
            public void windowClosing( WindowEvent evt ) { 
            System.exit( 0 ); 
            } 
        } ); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
